[package]
name = "escrow_manager"
readme = "README.md"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[scripts]
test = "snforge test"

[dependencies]
starknet.workspace = true
openzeppelin_account = "1.0.0"
openzeppelin_utils = "1.0.0"
common.workspace = true
erc20_utils.workspace = true
execution_contract.workspace = true

[dev-dependencies]
assert_macros.workspace = true
openzeppelin_access = "1.0.0"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
snforge_std.workspace = true

[features]
fuzzing = []

[lib]

[[target.starknet-contract]]
sierra = true
