[workspace]
members = [
    "packages/common",
    "packages/btc_utils",
    "packages/btc_relay",
    "packages/escrow_manager",
    "packages/timelock_refund_handler",
    "packages/hashlock_claim_handler",
    "packages/btc_txid_claim_handler",
    "packages/btc_output_claim_handler",
    "packages/btc_nonced_output_claim_handler",
    "packages/erc20_utils",
    "packages/spv_swap_vault",
    "packages/execution_contract"
]

[package]
name = "atomiq_contracts"
version.workspace = true
edition.workspace = true

[workspace.package]
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.10.1"
scarb-version = "2.10.1"
authors = ["Adam Borcany <adam@atomiqlabs.com>"]
description = "atomiq labs contracts for Starknet"
documentation = "https://github.com/atomiqlabs/atomiq-contracts-starknet"
repository = "https://github.com/atomiqlabs/atomiq-contracts-starknet"
license-file = "LICENSE"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true
common.workspace = true
erc20_utils.workspace = true
btc_utils.workspace = true
btc_relay.workspace = true
execution_contract.workspace = true
escrow_manager = { path = "packages/escrow_manager" }
hashlock_claim_handler = { path = "packages/hashlock_claim_handler" }
timelock_refund_handler = { path = "packages/timelock_refund_handler" }
btc_txid_claim_handler = { path = "packages/btc_txid_claim_handler" }
btc_output_claim_handler = { path = "packages/btc_output_claim_handler" }
btc_nonced_output_claim_handler = { path = "packages/btc_nonced_output_claim_handler" }
spv_swap_vault = { path = "packages/spv_swap_vault" }

[workspace.dependencies]
starknet = "2.10.1"
snforge_std = "0.38.0"
assert_macros = "2.10.1"
common = { path = "packages/common" }
erc20_utils = { path = "packages/erc20_utils" }
btc_utils = { path = "packages/btc_utils" }
btc_relay = { path = "packages/btc_relay" }
execution_contract = { path = "packages/execution_contract" }

[dev-dependencies]
snforge_std.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true

[scripts]
test = "cd scripts; npm i; npm run integration; cd ..; snforge test -w;"

# Visit https://foundry-rs.github.io/starknet-foundry/appendix/scarb-toml.html for more information

# [tool.snforge]                                             # Define `snforge` tool section
# exit_first = true                                          # Stop tests execution immediately upon the first failure
# fuzzer_runs = 1234                                         # Number of runs of the random fuzzer
# fuzzer_seed = 1111                                         # Seed for the random fuzzer

# [[tool.snforge.fork]]                                      # Used for fork testing
# name = "SOME_NAME"                                         # Fork name
# url = "http://your.rpc.url"                                # Url of the RPC provider
# block_id.tag = "latest"                                    # Block to fork from (block tag)

# [[tool.snforge.fork]]
# name = "SOME_SECOND_NAME"
# url = "http://your.second.rpc.url"                         
# block_id.number = "123"                                    # Block to fork from (block number)

# [[tool.snforge.fork]]
# name = "SOME_THIRD_NAME"
# url = "http://your.third.rpc.url"
# block_id.hash = "0x123"                                    # Block to fork from (block hash)

# [profile.dev.cairo]                                        # Configure Cairo compiler
# unstable-add-statements-code-locations-debug-info = true   # Should be used if you want to use coverage
# unstable-add-statements-functions-debug-info = true        # Should be used if you want to use coverage/profiler
# inlining-strategy = "avoid"                                # Should be used if you want to use coverage

# [features]                                                 # Used for conditional compilation
# enable_for_tests = []                                      # Feature name and list of other features that should be enabled with it
