use openzeppelin_utils::snip12::OffchainMessageHash;
use core::starknet::ContractAddress;
use core::poseidon::PoseidonTrait;
use core::hash::{HashStateTrait, HashStateExTrait};
use openzeppelin_utils::snip12::{StructHash, SNIP12Metadata};
use crate::structs::escrow::{EscrowData, EscrowDataImplTrait, EscrowExecutionImplTrait};

impl SNIP12MetadataImpl of SNIP12Metadata {
    fn name() -> felt252 { 'atomiq.exchange' }
    fn version() -> felt252 { 1 }
}

const INITIALIZE_STRUCT_TYPE_HASH: felt252 =
    selector!("\"Initialize\"(\"Swap hash\":\"felt\",\"Offerer\":\"ContractAddress\",\"Claimer\":\"ContractAddress\",\"Token amount\":\"TokenAmount\",\"Pay in\":\"bool\",\"Pay out\":\"bool\",\"Tracking reputation\":\"bool\",\"Claim handler\":\"ContractAddress\",\"Claim data\":\"felt\",\"Refund handler\":\"ContractAddress\",\"Refund data\":\"felt\",\"Security deposit\":\"TokenAmount\",\"Claimer bounty\":\"TokenAmount\",\"Claim action hash\":\"felt\",\"Deadline\":\"timestamp\")\"TokenAmount\"(\"token_address\":\"ContractAddress\",\"amount\":\"u256\")\"u256\"(\"low\":\"u128\",\"high\":\"u128\")");

const U256_TYPE_HASH: felt252 =
    selector!("\"u256\"(\"low\":\"u128\",\"high\":\"u128\")");

fn u256_tagged_hash(value: u256) -> felt252 {
    PoseidonTrait::new().update(U256_TYPE_HASH).update_with(value).finalize()
}

const TOKEN_AMOUNT_TYPE_HASH: felt252 =
    selector!("\"TokenAmount\"(\"token_address\":\"ContractAddress\",\"amount\":\"u256\")\"u256\"(\"low\":\"u128\",\"high\":\"u128\")");

fn token_amount_tagged_hash(token: ContractAddress, value: u256) -> felt252 {
    PoseidonTrait::new().update(TOKEN_AMOUNT_TYPE_HASH).update_with(token).update(u256_tagged_hash(value)).finalize()
}

#[derive(Drop, Copy)]
struct InitializeStruct {
    escrow: EscrowData, 
    escrow_hash: felt252, 
    timeout: u64
}

impl InitializeStructHashImpl of StructHash<InitializeStruct> {
    fn hash_struct(self: @InitializeStruct) -> felt252 {
        let hash_state = PoseidonTrait::new();
        hash_state.update(INITIALIZE_STRUCT_TYPE_HASH)
            .update(*self.escrow_hash)
            .update_with(*self.escrow.offerer)
            .update_with(*self.escrow.claimer)
            .update(token_amount_tagged_hash(*self.escrow.token, *self.escrow.amount))
            .update_with((*self.escrow).is_pay_in())
            .update_with((*self.escrow).is_pay_out())
            .update_with((*self.escrow).is_tracking_reputation())
            .update_with(*self.escrow.claim_handler)
            .update_with(*self.escrow.claim_data)
            .update_with(*self.escrow.refund_handler)
            .update_with(*self.escrow.refund_data)
            .update(token_amount_tagged_hash(*self.escrow.fee_token, *self.escrow.security_deposit))
            .update(token_amount_tagged_hash(*self.escrow.fee_token, *self.escrow.claimer_bounty))
            .update(if self.escrow.success_action.is_some() {
                (*self.escrow.success_action).unwrap().get_struct_hash()
            } else { 0 })
            .update_with(*self.timeout)
            .finalize()
    }
}

//Computes the init message sighash
pub fn get_init_sighash(escrow: EscrowData, escrow_hash: felt252, timeout: u64, signer: ContractAddress) -> felt252 {
    InitializeStruct {
        escrow,
        escrow_hash,
        timeout: timeout.into()
    }.get_message_hash(signer)
}

const REFUND_STRUCT_TYPE_HASH: felt252 =
    selector!("\"Refund\"(\"Swap hash\":\"felt\",\"Timeout\":\"timestamp\")");

#[derive(Drop, Copy, Hash)]
struct RefundStruct {
    escrow_hash: felt252,
    timeout: u128
}

impl RefundStructHashImpl of StructHash<RefundStruct> {
    fn hash_struct(self: @RefundStruct) -> felt252 {
        let hash_state = PoseidonTrait::new();
        hash_state.update_with(REFUND_STRUCT_TYPE_HASH).update_with(*self).finalize()
    }
}

//Computes the refund message sighash
pub fn get_refund_sighash(escrow_hash: felt252, timeout: u64, signer: ContractAddress) -> felt252 {
    RefundStruct {
        escrow_hash: escrow_hash,
        timeout: timeout.into()
    }.get_message_hash(signer)
}

#[cfg(test)]
mod tests {
    use super::*;

    //Test cases generated by scripts/tests_unit/sighash.js
    #[test]
    fn random_init_sighash() {
        let escrow = EscrowData {offerer: 0x22914dcabff09469693e6363a8ef1fbe3cf7c4053a6fa919c8c943e17be103a.try_into().unwrap(), claimer: 0x59d79819bbceb92de320451e363b4120f28f11c90f0b6a9129793d3503699f9.try_into().unwrap(), token: 0xa84ca0378c921a1367c925be6da39e36b26a51917844780b8e3ad64406125d.try_into().unwrap(), refund_handler: 0x203a5460badc742cde2c55830cef96819dcc7724223221337071d89a31df761.try_into().unwrap(), claim_handler: 0x7490df73ddfb2c55a1d681b72e469149fb72ec9488b7c9a5316b38077177e83.try_into().unwrap(), flags: 0xd7deaaf5f454602d3bcb6d051341dbaa, claim_data: 0x9f09a27fb0bf5873101b3d5896351f7d80f06a85a07c6a573184027162365d, refund_data: 0x2b0e6f6b1926f631f05c7f2ef28cf1c27e2cba5325a75fb13a4bda10f94077, amount: 0xb00adc00645189c3b9e3432e06defd5fb8299ee6f561212e0409284244ea2dfe, fee_token: 0x2b316175b8873a8a0ff6f20ea842902859b6e70eb20600f807ec67eeb8cec15.try_into().unwrap(), security_deposit: 0x68b6701b18d0bedc06ce90a98af4d939fa241d9bc3b820e2075daa7397d17d59, claimer_bounty: 0x90b7cd52d5b14193553b18452ae76c136723c45d165a27bbb2f921eeac3e159e, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0x685ddd941a95cd14743a80ba8d84985eb6fadab9ee94eb3e16173161729fc8, 0x1e6d9536759991b0, 0x499c27e46499b74da25f586d1aa0d123a87982d620b9a53a4c0301615f3f0c8.try_into().unwrap()), 0x40624ac89fa7084fbd2d1698f4452ef2ca6dfe2d56e24633a5029a00bb36d2d);

        let escrow = EscrowData {offerer: 0x7cf5d39d4107ff680ab3e51e2184437d45f6556fdc80a26cb19b9b22c0bcc2b.try_into().unwrap(), claimer: 0x7ebddf5032eea9c52a10a82bac4ea27632d76bc07e1102c55d812321f4917bd.try_into().unwrap(), token: 0xf5ffd97102760b7916912f1703cbc530b53969272a7e3141dee1a06a0aacfd.try_into().unwrap(), refund_handler: 0x24aad8a8c8a851032f801f4d62c0d591a4e2004914e3bb516a5cc115dbda812.try_into().unwrap(), claim_handler: 0x2be43304847235a55175fc83d9e750333c0c6d4d346f4d536cbb694f67d31f7.try_into().unwrap(), flags: 0xa802ab1ee4fbccc954638d14379d4899, claim_data: 0x0f370180085668ddfd108d299b176ca37caf8c17bd54e14d0e85e47b6eced2, refund_data: 0x7518b20dd05ab1a3d4912285347397366e45e54bfdcf7af04a13c7370666b6, amount: 0xdef8cada4e78b6e515b981e0a6b226545dc16e7b5c0017bf6b6072db4ed3f91e, fee_token: 0x19dc655a4781d488962f8e6146fc6541f8566486219db752ff9a038b0a6ff10.try_into().unwrap(), security_deposit: 0xed3b6186e7cc0b98f8411290fea2e7638f74151e5bfa87b708d168a68d390f7e, claimer_bounty: 0x86e65a74cf5820097ba5c43b82e7156fbd538aaf2136b465a66b768fa1a23ec3, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0x1579382f1ea54fd2160ea6674d289a244e74d9b843e54b8ed800ae1f271a8e, 0x619e896ad20070aa, 0xfa1d008b8ccb4a77bb35ce45e5f1afbdf5ed5ed9f5b7f50ea66183acd440b4.try_into().unwrap()), 0x6ac7734cbe36e0df100ebd7d2ac6f7458ab14ae0f1c9c992b72da0581af253a);

        let escrow = EscrowData {offerer: 0x7ba6077d7e36afa2181dc3cae05b9cb9e3e043ccddce854329c88838a510383.try_into().unwrap(), claimer: 0x5380bb59b65dfb45f4653591d17dc18907980d59bdf9ef22c8607492663ab1f.try_into().unwrap(), token: 0x7b4779eae44ef0d8a51e1601e6ecc92eff9551881d680cba9b3489e03900df7.try_into().unwrap(), refund_handler: 0xc38f4d196725e532372e2a1c20003361aa33217e45e205e57e8707e4a37772.try_into().unwrap(), claim_handler: 0x11a98cd8fdb80b9f5963411a1c4a1f2edc1162382ca4a406a409cf8e28ee67b.try_into().unwrap(), flags: 0xff3d032bae33d233727e5f816b99dedf, claim_data: 0x8ae901e9218c700f97ac1afa421caf1f4db3008ec9e9332c00e606917ffb5a, refund_data: 0x7fa4115961d82e76308ad5b62e4d460d8a0207752b450f956d468d31cce4d9, amount: 0xbb2fdf5af4ae609d135d9f495eba5ee1d65860e9ee7c81983c56b73688d87e54, fee_token: 0x4d7d9383b673e85910cc5e217163de88503ee3629dbe85399201ff023621ae4.try_into().unwrap(), security_deposit: 0x4a6413a645a7f96c72d701c8825ca013047a4bbd7592c69c4c9a3a32f179c02c, claimer_bounty: 0xc52734692646ca04d6ae545666490140bf82df92aaa45b4d84179ca902541201, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0x3375201c5bc59c2c27553868c4319c01208ac8ad054f8c8c08e8e1a6ba8da5, 0x7d7ff9fda54b6366, 0x48e2b01b32b31c690668684ae28139cc28ba1cfa0e46edee80a7fabcf913ecc.try_into().unwrap()), 0x60e583acbf3a12d8349421b8514107730464ca257c5863e568cc8a7339051ca);

        let escrow = EscrowData {offerer: 0x3250b639db2147f744003da9df09545af8db6a501c86dd28a231a94f4648ade.try_into().unwrap(), claimer: 0x19f523f7f144e45ca84503cb40c7a10c643458ac43b2f45444d854538337168.try_into().unwrap(), token: 0x3b8c6807dc950cb9b3f33ed265bdf3e26cf493023e2b2b0bd3a3a5120e7b0c3.try_into().unwrap(), refund_handler: 0x6cb019566b5db5173caf8e02256d4cbe64260be501c72146457eb13198e3aed.try_into().unwrap(), claim_handler: 0x1617f6e17059cf15c607dcc3171e37006632e62837d75f1b483ec95c2756784.try_into().unwrap(), flags: 0xd4020792ee5286092bfed42ec533be89, claim_data: 0xda9648bfe3721b0b892b447e4761cdbcf0f76e458026d9c11624842439dcd6, refund_data: 0x447468189f2cfa6fcad55a948448a4478457874214c780a0e66c8429eeceab, amount: 0x0cffbca3e8582199b40824b24e591e0897a557c202bc2f10c07ea8f9a6325104, fee_token: 0x6e62f0674cf4832a9bab24a4e17ddc475c41f684128dffca78c32e0369db085.try_into().unwrap(), security_deposit: 0x0ee0cf6ccf13bf739c05cc7154e6e0f806480d5e60cfafa143b12428b2a865f9, claimer_bounty: 0xfc89915bc7e0ddc94323175178f6dd72824a603df16c9058d040a7e06ff2d21e, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0xc312be489e08b9476b6ec332f5330a71f270f9ffa88e43582eda02b47c26fd, 0x4d9765d2abd6b69b, 0x27d07f15d68203c7521a0ba620149e49188592bdd2505bcc27e47c2ef3d8087.try_into().unwrap()), 0x349efcb3fe2e9d8d4ac850d2836a992717cf4d910c5c20833067e0a99c16f95);

        let escrow = EscrowData {offerer: 0x75b04e895ebe96414f4c13b32d69b30e9692d20effb9221e6882f1330cd002d.try_into().unwrap(), claimer: 0x1668a10907302808d0e3072a08e2bf4bdcec265cd23726907a4b99ff6587192.try_into().unwrap(), token: 0xfada0d8c3c81e781445e6bc71b148a395b8b7faf5b17b5ba41f279c8871bb5.try_into().unwrap(), refund_handler: 0x39d2a3d53d8d45674f30e979389489c83e1dd5332bb13e79df449bbd70bb758.try_into().unwrap(), claim_handler: 0x4e7219f354956dab4a72ec316178c4ab2076f683e28e06fe4da4cb3f3562ce0.try_into().unwrap(), flags: 0x83612ff68b3899e161d24fa474a5b9a, claim_data: 0x79b6aeb1987d17c43372ef1f11398a15ab6a798de2cde8ea3563abc5ffc229, refund_data: 0x11cd64f00c83bfad6601b12577fa625544afc85d62b07be7f32567c0bf64cf, amount: 0x8001e26f0cba3d23284c1338c5c6e0fba967f17692b7ac6622e856995b0440bb, fee_token: 0x235f1d154f25ffbd7a86e68dc3f4c748aa232d75c657ed66f90b36b33aa31e0.try_into().unwrap(), security_deposit: 0xcffffaa3e0d17ffdfd7360ecdff63b3053c7dc3e5b166bb26a317aa7973a9de0, claimer_bounty: 0xbcc83ac107a7fcb0b50f2e479e9b7f8f24d4bab96480679979c412581d8a3291, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0x3fe9a8b9223d22b4785b942199e3e5a8b3d5e4edd5a7cda7edf6ed9a6b8299, 0xa81534f48f5127f2, 0x22a3426d0bc9383ee802513ab3a534b951d13e9bd5bc0021644394c9953a7a1.try_into().unwrap()), 0x6d558b5e1ab1fccb3a7bafd82a5de0d9648fccbb20ee621314da516072130a2);

        let escrow = EscrowData {offerer: 0x4819831333d5a64295b2c02ef4fb6b397742e30ec966f24dbddcb4b2c09d607.try_into().unwrap(), claimer: 0x62f32d812e2d843d74de7d0c91c2d943f2ef61a1711b5023d6f93a5ef0c98c3.try_into().unwrap(), token: 0x70b863adf20ed127752f2e0e519a84f031641f66b1b2675f4003cb43bbf11a2.try_into().unwrap(), refund_handler: 0x4c19d20abe829378a9ef359710dd645425ca90804d588b4a32e6871fbece25d.try_into().unwrap(), claim_handler: 0x5a93a4e9f3343ad6e28636d499cbe6a4e4cf77e7ecbaedc2c770a85b12c131.try_into().unwrap(), flags: 0x75ae4bd6dad39da28a34d1039f98afd6, claim_data: 0x921ae3522caf6d00fe0e97fac6f390b71fd70c0b946ede5cf4919617f6f508, refund_data: 0x03bce403c29cf3ae3cecaa31fca8f304b8ee6e4e716d9ff1298e01af52885a, amount: 0x8bd9351b934fd7c8e1a1242fdf2167a180eca4c335cb5c90da44c06a32830896, fee_token: 0x4c4ad37d23df30198aeea5d3c1914af2ecf77383df740a69c8a14dbab81113f.try_into().unwrap(), security_deposit: 0x8b7d7fe96ebc0fe97875cf5929a3dddcd29bef60fb6f154504701f2a92bc9a64, claimer_bounty: 0x1f992c6e57b9baad78edf6b9f2b322f11fe500744cc443a126805fddd7ab1da1, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0xb91b7c512fc16b33ca349c11c65ac23ed4b72b5f01549d5ed378b030c089ab, 0x73c462d4ad7ef0a8, 0x4fea4ac10a34d09b31c56652f3faef8c68f93dd9ff3bc7930be82445c58ffd3.try_into().unwrap()), 0x725a5346f2b59d5eea3005dbc20cd8fa20b0fbd969916bde857653bfb5b9564);

        let escrow = EscrowData {offerer: 0x2567f88ae28a02749f6404dfe6b72333f2ba889c1bf6385bc4c42f7232db24f.try_into().unwrap(), claimer: 0x794cd515a1b016ff6216ed674e15615b5eb347634853e6b6124e48428d5ec09.try_into().unwrap(), token: 0x22875a0e17a2b141144e2a091be6a0ecf9491b5ddf4f2f3d4b75749afb9f5eb.try_into().unwrap(), refund_handler: 0x3c1cb77736d10818b0e40a44c00b4e019bdee54eed127596e2d2499c525a247.try_into().unwrap(), claim_handler: 0x551e3b25e2d5d6040e2052a4f9f44942c304d475382b8143ba6ade1eef0b186.try_into().unwrap(), flags: 0x968200be0305952070339d0cdc4aa2d7, claim_data: 0x46768a23049010c5be793894e10de9da60240a629d53ade72dafe03284cc09, refund_data: 0x694138ffcc75f841fdcf4caa35eb4ccf753f6eb2ec8d944e2462a3fee25279, amount: 0x3cfbc9ed841e2d8d5c5f7607fa593aa63b52e97fce2fa1feec14b304fe3f244e, fee_token: 0x1b415936ca41654737e7e0e96c404e5679c34e41f8a295ebd5bd1e764f39056.try_into().unwrap(), security_deposit: 0x4c10f4a8d2895745b65d7e606cb643d13abb7c14b48b1c31cb544707b1876c75, claimer_bounty: 0xd5e0102726e48ffad5e3e820b0df3b7d6fe939cbfaaf7e1935c8b2a3d3538479, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0x9306f2462283198c0ee2978d42ece936bb3abd3d559b576b1f6212b8295c26, 0x3e1f3f591e88f73f, 0x3bbd0a93c313330ebb11362df871a7a3eb33c1fd7b260d74061a0f30228d888.try_into().unwrap()), 0x3bb3fdc056763f43f334ee786384307a80deb2cfa499655d6af9364ee201cf9);

        let escrow = EscrowData {offerer: 0x561a1fc0010c0d8bb1424755cd64179e3353495fee252d11675873ec6aa5f06.try_into().unwrap(), claimer: 0x1e5a01ada0e1724300645a617b38d81ca31e8fbf1df920ab759cebbb09e808c.try_into().unwrap(), token: 0x718ac24ba4e1bcab5d8193cda249222001b905e1d4d5801511c334419aae9fc.try_into().unwrap(), refund_handler: 0x4ee42d06f7ebcb4ea2c13d4c07598a8ae65661aa197fb9b1526590944bca4f0.try_into().unwrap(), claim_handler: 0x3f3b16553a389d878f917380887bb1be31589e243ce797aff75be34ffc487fe.try_into().unwrap(), flags: 0x572d5f35302aabadfc1e56bc7cbf8921, claim_data: 0xb8337e77ec46646bd15b2d488641382ae87be0e5f7e75127ed769c0a6ad1dc, refund_data: 0xc249a0360bd6f230f9f6878f3669ee17cdf86ccaa23e439898fbd5ad6205da, amount: 0x805d1d59992782d57d44441f848344bdb723686f4f1c912909ec6173e3f9ad3d, fee_token: 0x20c5fc29f16b513ef56c3a6cf421778313af293333d01ffb901568b02f4636e.try_into().unwrap(), security_deposit: 0x196bfde865b6f5ba2ed6991c005c7e79f3862e63c60b5daff273225f1e6cc51b, claimer_bounty: 0xa106fd99c890da1ced8e4c4ab320d507d590804aacd36829567fe876475181be, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0xf86312504d4bf2348809587cfcc2400b6c63344f94f4151d90ace8e8f82a17, 0x14bf2582e609e42a, 0x1d5b1046f25b31b72a2ca747ae32c83cc03ddcbe3ea4217f40941f1e84c051c.try_into().unwrap()), 0x12b374f98536785906a1992ad144d6e11c2a8de9c81fa1de80241bf3ab0d856);

        let escrow = EscrowData {offerer: 0x55590deefcb7aca1d0042ccc5d3677cd8f37e96119eb760a58ac5071042cd32.try_into().unwrap(), claimer: 0x3ac4c49822e7ded1f05dca97acc9bd1aed4b6b5f38423768a61ee48d45ec86b.try_into().unwrap(), token: 0x3a800e7c9249dcfea5c4ce0092ad9b532d9a430e32e253725326166189fd31c.try_into().unwrap(), refund_handler: 0x621157754526a3cccc5e44e2c7c49a176d783be94a16f49d8a285db5993cd98.try_into().unwrap(), claim_handler: 0x49c0d486917485db3b176411271784b60a51a56b3242e8126dfc595551f8255.try_into().unwrap(), flags: 0xb212fbded37d6c0eb78ceae731ab625b, claim_data: 0x07b1f4e0e6c52719143594e7a3d807136ff48fdcc2f6187ed0cba656181e6d, refund_data: 0x3a5dabddd53ec2a5cb627dba36466ce21a253bd6d36ab9f0b3023f81a04288, amount: 0x0b85ad2058f0391e4e52df30a7fce666e06eb885972fde059e1a689da3888439, fee_token: 0x6649d54ef64ba29e6f4f3f30df98143049ff73329c272b0b721c566714ea4f1.try_into().unwrap(), security_deposit: 0x8bdb4da2f73a911d3f3b796df41844ec59df9aa76ea607ee8382cd9fd2798e6b, claimer_bounty: 0xb6b9ba8d56895344d5d5ddc68a7e99226ffb9ecc7f7a510695ef15ea0ddc55ba, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0x1034452236b301110eaf259b7465f64491810121bbdccd37aeed26b0b2c907, 0x1dc8b01c1b960656, 0x2ef08d710021a091b6404804debacf9485fddca076d81ed606708980f6bd1e3.try_into().unwrap()), 0x51a7dd1c0155a181007193f17ed99da67947957a6af0dba115de0a2853106eb);

        let escrow = EscrowData {offerer: 0x181d751e39b8966e122007c4e19b55ca87b383d424b2aa99d7e76da0ad6afb1.try_into().unwrap(), claimer: 0x41e44f60263e2885ffbd4d30b8e0eed18ef3224b984363b22a021bbb5da4519.try_into().unwrap(), token: 0x64ca0eee8967a1edf7c487170a5055a29ebf9072228773a654630562ddd073b.try_into().unwrap(), refund_handler: 0xe16d9aeaa1504dea1090e16e4e2cf82fb4e2bdc905d9078396a42cc0e7870f.try_into().unwrap(), claim_handler: 0x590180251f9363e8374a35d512cadbf1db3e2f6e80eed1fb87e7107f8d5c04f.try_into().unwrap(), flags: 0xba3fc1d08d7cb86331d2005af04204e8, claim_data: 0x3adf1124ef5dae08c984ebab6900032f20fd79ac0feaac615ca30272a184a5, refund_data: 0xfea790e75e7f4748998b513d55ea91eef06c1dbea12da77b050959b61e1a23, amount: 0x3724d69917ed2f2418e3812610536150a60b1aee1b383aea5b3d80f87861d2cd, fee_token: 0x72632e6feab446a1f78549b5c76d25a5cd7ecf0037629625996444904406480.try_into().unwrap(), security_deposit: 0x9edd8a25eca40aed37691ceebfe09244b394ee6616cb998ecf2d115345e10131, claimer_bounty: 0x4cd6ad8ef786469da124a024d77d8f438ba2b1bc975788b73a40724af0842c17, success_action: Option::None};
        assert_eq!(get_init_sighash(escrow, 0xd23ad8023b5740b3bcb96847103938f6553006bd6fbb8b8b6282df663fbedd, 0xfc92f75e1cf49c23, 0x4329e1ca1584b9d72a4e78fb064dc4fc05e821502a27035f26ad62c26d29764.try_into().unwrap()), 0x33b197d7dd5023d6b800e1bcff908808095fb6241f02e63de6ffd6e5c2720be);
    }

    //Test cases generated by scripts/tests_unit/sighash.js
    #[test]
    fn random_refund_sighash() {
        assert_eq!(get_refund_sighash(0x852a3b8b3b47b59b667bfd3da6858b06f01f6a59bbb8ca1f38c9436796e13f, 0xa153864f3b2fad8b, 0x4f2a98641be380e78b167a0ccd81da9f31e4ca8638a9b5623ad3701c77723ae.try_into().unwrap()), 0x25cea43ab2dd83ff1a2656806374d514cd4a45d3e0c61a47ebacbf50bc7beec);

        assert_eq!(get_refund_sighash(0xc6ceb22b8a29c80b5b981c39cc5363aab6bb5cc03acbe297a952445cbba5e5, 0x4dc3ec78f32361e6, 0x4810abab3576f212a629128ce03114a73c4025a33facedbe6307ae8b9a21ac3.try_into().unwrap()), 0x4caa4b3c8941efba88c43ce8dc05a2d10f325609067355be5690fc8e00c2edb);

        assert_eq!(get_refund_sighash(0x7f78a1f440dc21574f72261fc593760be7e84b0050b6dbf7a4815775380a5c, 0x5a7e2b2b8b4b62df, 0x20dde7c18650bb22de3f30cf982a8a43e210cc4bfe6f194d54c0dd5b8666328.try_into().unwrap()), 0x2dc64fc9eeb261d00c78a5d031aa5169a1c90717c4057cc43067b612218f2e);

        assert_eq!(get_refund_sighash(0x2b61ca286ef46127ea04c3b2339c41c47baa81b3b4e111ba8781fa62313a39, 0x7e80747d9880a826, 0x261994b269672b16cafd3ac60ea4c61a24cd496827b720b3cfe3e5b6d98b566.try_into().unwrap()), 0x302cacc44c86398c0791878de74bfd6f4532c0590a36f33a301cefbb78421d8);

        assert_eq!(get_refund_sighash(0x35daf34366d7991ad874ccdd508def90efe726135e6b8fb71230fd4b09774c, 0x8968aa83cfbb5cbd, 0xa727377df66612df45bc7a3c20372ea3e6303eeb8dcd49edb79a2194942cd1.try_into().unwrap()), 0x3295d7968272be7c4d707ec8050a9dea4f5921b810b22f32d99121c5a348062);

        assert_eq!(get_refund_sighash(0x5f43b3623990bd1fb295280918f90e648a7b8ce0ee2cab692e6d49dd9765b6, 0x6acb99eb64378551, 0x4493754678ce75acbfd99f7fa805324fb5d954afe9ea61cbb63d51190932274.try_into().unwrap()), 0x7c07d6fe7f0fbd68ed7a1aa0d843c1b52f64eab6d5cab9d929c9ee95e5169f6);

        assert_eq!(get_refund_sighash(0xc597b501c46b55041c7cda2548dd581a97cce5738b9e6a19337a77ebaf971b, 0x83d472777629015f, 0xebc88c10f8f6f503f900c9c80c9f1fd15e93ed73b261dd977e596ed52cd689.try_into().unwrap()), 0x6c2fe66d5773ccef6eb05a80b04d846f3b1b1511e1106b5172de121066a6bff);

        assert_eq!(get_refund_sighash(0x437df73b7e1fb4f7b4dc7fbbf391917a9fbdfc2b6f4385d6c2a6f05336b0e5, 0xc68c2a2a92d58c70, 0x735405e307e9f6f7b456f9f68ab530cc938164f7ba7f1ddb495317b01c4fca2.try_into().unwrap()), 0x3ba814c3275c42fac0ad4ff3ac4182ca239d2f2113a6780b940d96a1b6366c5);

        assert_eq!(get_refund_sighash(0x6b3c0ddd69b77686d89156bebfcac97f74266b95b188f512264f982960565e, 0x41a5856cfe04a190, 0xfac4f979f56ae50c54b37caaef2524e556006be6153f8c9157576860b12382.try_into().unwrap()), 0x308fd4d1206e8f844adfd5ad6a62c682a89ae267fa2b828f299ac31aaa60009);

        assert_eq!(get_refund_sighash(0x11562e41a2a8a4b7f76a651b4de71a80510fadc04936e60bc23d20c706493b, 0xb2b56a9166aa0902, 0x3ee6deede25ce8080cbf4809916b6a40b70609917321729a67855f2b7e8e850.try_into().unwrap()), 0x16f25173bf94a5b484f370d5fca75e68479c7a0ba88183aeb337ac1a1e6e3dd);
    }

}