use openzeppelin_utils::snip12::OffchainMessageHash;
use starknet::ContractAddress;
use core::poseidon::PoseidonTrait;
use core::hash::{HashStateTrait, HashStateExTrait};
use openzeppelin_utils::snip12::{StructHash, SNIP12Metadata};
use crate::structs::escrow::{EscrowData, EscrowDataImplTrait, EscrowExecutionImplTrait};

impl SNIP12MetadataImpl of SNIP12Metadata {
    fn name() -> felt252 { 'atomiq.exchange' }
    fn version() -> felt252 { 1 }
}

const INITIALIZE_STRUCT_TYPE_HASH: felt252 =
    selector!("\"Initialize\"(\"Escrow contract\":\"ContractAddress\",\"Swap hash\":\"felt\",\"Offerer\":\"ContractAddress\",\"Claimer\":\"ContractAddress\",\"Token amount\":\"TokenAmount\",\"Pay in\":\"bool\",\"Pay out\":\"bool\",\"Tracking reputation\":\"bool\",\"Claim handler\":\"ContractAddress\",\"Claim data\":\"felt\",\"Refund handler\":\"ContractAddress\",\"Refund data\":\"felt\",\"Security deposit\":\"TokenAmount\",\"Claimer bounty\":\"TokenAmount\",\"Claim action hash\":\"felt\",\"Deadline\":\"timestamp\")\"TokenAmount\"(\"token_address\":\"ContractAddress\",\"amount\":\"u256\")\"u256\"(\"low\":\"u128\",\"high\":\"u128\")");

const U256_TYPE_HASH: felt252 =
    selector!("\"u256\"(\"low\":\"u128\",\"high\":\"u128\")");

fn u256_tagged_hash(value: u256) -> felt252 {
    PoseidonTrait::new().update(U256_TYPE_HASH).update_with(value).finalize()
}

const TOKEN_AMOUNT_TYPE_HASH: felt252 =
    selector!("\"TokenAmount\"(\"token_address\":\"ContractAddress\",\"amount\":\"u256\")\"u256\"(\"low\":\"u128\",\"high\":\"u128\")");

fn token_amount_tagged_hash(token: ContractAddress, value: u256) -> felt252 {
    PoseidonTrait::new().update(TOKEN_AMOUNT_TYPE_HASH).update_with(token).update(u256_tagged_hash(value)).finalize()
}

#[derive(Drop, Copy)]
struct InitializeStruct {
    escrow_contract: ContractAddress,
    escrow_hash: felt252,
    escrow: EscrowData,
    timeout: u64
}

impl InitializeStructHashImpl of StructHash<InitializeStruct> {
    fn hash_struct(self: @InitializeStruct) -> felt252 {
        let hash_state = PoseidonTrait::new();
        hash_state.update(INITIALIZE_STRUCT_TYPE_HASH)
            .update_with(*self.escrow_contract)
            .update(*self.escrow_hash)
            .update_with(*self.escrow.offerer)
            .update_with(*self.escrow.claimer)
            .update(token_amount_tagged_hash(*self.escrow.token, *self.escrow.amount))
            .update_with((*self.escrow).is_pay_in())
            .update_with((*self.escrow).is_pay_out())
            .update_with((*self.escrow).is_tracking_reputation())
            .update_with(*self.escrow.claim_handler)
            .update_with(*self.escrow.claim_data)
            .update_with(*self.escrow.refund_handler)
            .update_with(*self.escrow.refund_data)
            .update(token_amount_tagged_hash(*self.escrow.fee_token, *self.escrow.security_deposit))
            .update(token_amount_tagged_hash(*self.escrow.fee_token, *self.escrow.claimer_bounty))
            .update(if self.escrow.success_action.is_some() {
                (*self.escrow.success_action).unwrap().get_struct_hash()
            } else { 0 })
            .update_with(*self.timeout)
            .finalize()
    }
}

//Computes the init message sighash
pub fn get_init_sighash(escrow_contract: ContractAddress, escrow: EscrowData, escrow_hash: felt252, timeout: u64, signer: ContractAddress) -> felt252 {
    InitializeStruct {
        escrow_contract,
        escrow_hash,
        escrow,
        timeout: timeout.into()
    }.get_message_hash(signer)
}

const REFUND_STRUCT_TYPE_HASH: felt252 =
    selector!("\"Refund\"(\"Escrow contract\":\"ContractAddress\",\"Swap hash\":\"felt\",\"Timeout\":\"timestamp\")");

#[derive(Drop, Copy, Hash)]
struct RefundStruct {
    escrow_contract: ContractAddress,
    escrow_hash: felt252,
    timeout: u128
}

impl RefundStructHashImpl of StructHash<RefundStruct> {
    fn hash_struct(self: @RefundStruct) -> felt252 {
        let hash_state = PoseidonTrait::new();
        hash_state.update_with(REFUND_STRUCT_TYPE_HASH).update_with(*self).finalize()
    }
}

//Computes the refund message sighash
pub fn get_refund_sighash(escrow_contract: ContractAddress, escrow_hash: felt252, timeout: u64, signer: ContractAddress) -> felt252 {
    RefundStruct {
        escrow_contract: escrow_contract,
        escrow_hash: escrow_hash,
        timeout: timeout.into()
    }.get_message_hash(signer)
}

#[cfg(test)]
mod tests {
    use super::*;

    //Test cases generated by scripts/tests_unit/sighash.js
    #[test]
    fn random_init_sighash() {
        let escrow = EscrowData {offerer: 0x14ad23e644b0c3ca86f9e060d35d780db37b583bffaea6c5a4d385193eea906.try_into().unwrap(), claimer: 0x2a3e6f5c9e7b794c1d75b53cdad2258c41f0efcdd001754d364bede86a10c76.try_into().unwrap(), token: 0x143bfdb3a48fb48ce371a44534e12b893504dbb3b8bb8d8917bb86bddd9609c.try_into().unwrap(), refund_handler: 0x10a533e79201b4c18ba70f9292921f44f2f9ee1345f312ef2b05b53668935c1.try_into().unwrap(), claim_handler: 0x661a54a07c0f92e853e0223b64e5e690633ef77366d43d17ebc3f258edf7df8.try_into().unwrap(), flags: 0xd93a91a46b1f9e98fd70efa339be708d, claim_data: 0xb7e5030e61998fb5d3aa6a970b7ae3b419046c3ac7d9643e7904e7b55e7660, refund_data: 0x9d3cdd6027b29353056654b231f91898bf2c9e17559c2e5483c2d6927fd338, amount: 0x4d4a0394ad4fd9aaf65bedcbd3eaa66cf6412254baeb687ec0f91ed0d337376a, fee_token: 0x37fc57a47a60434d3ed9f1afbeec8fd707d6e01901f6d3a543f23f547ad958c.try_into().unwrap(), security_deposit: 0x2b4881753321d4f25a849b5f52565d0b32fd13f6f83cb0e04eefff2e311ba2d9, claimer_bounty: 0xb0dc843ed3ddc138ba44a1161eb87a204cb12e4aeb3a8395aa3e54ea83e74541, success_action: Option::None};
        assert_eq!(get_init_sighash(0x14cb424c27faa97637089ca4d63e95bc1ef6df3562a9a6bca9f27e4f302fc29.try_into().unwrap(), escrow, 0x560f56b15368f0a6bad28ecdab56414f1159ea9fc0037c87e32c5dc161ba3f, 0x16ebed407091e11a, 0x52dd5e723363b25ddd58ea703cddd76f4395c13e778b5814312f4d59875ed96.try_into().unwrap()), 0x4ad2c4f63abcca0624002f0423043bc8118ab748ea4acc821cf055a5361f45);

        let escrow = EscrowData {offerer: 0x8ac85b0126fbd260563c7e15f87f5833ca0ed632db6e68596a6cd1df410125.try_into().unwrap(), claimer: 0x3b649bfa844abd88273005ee22e3850e23d3477d7c9a75f9a51aa3efa9c9f89.try_into().unwrap(), token: 0x12a822096d60ec03cdab5404b360543b2a61b5e1974dfa8411e616c89f55b27.try_into().unwrap(), refund_handler: 0x76c3d87c2b0528aa8b424c00943bef59630443b27edf41b470e53bf86c91cc0.try_into().unwrap(), claim_handler: 0x28ed204d7002dc5d50000bd64edb7a7993a35c1755cdefc3dc141f86d1e6164.try_into().unwrap(), flags: 0x5e997d0b415e8a0bbcb7852ba912e43, claim_data: 0xb1efbaa219715763324e9b4fcd9719e680f01543f85e1366a24204690ba83e, refund_data: 0x93b87cd412134af88bf87a8ffdbc2d06bc5af1eb6bc57f6e863de5daff38bc, amount: 0x092e6384d73ee521a29f5a8266f2bacb032bac373c55bbf679dc474abc17b67e, fee_token: 0x1a679ac87aedeb465fe35a2cdc46e792e116501ee97e2290c464418a0f38656.try_into().unwrap(), security_deposit: 0x818601b8dfb49772d022c1dce0cd2601d9a8d649c1278423dddac72826f84372, claimer_bounty: 0xabef1a267c8ab81d642c1ce1cef77d2d23d04274bde5ba353813c34f8f33e39c, success_action: Option::None};
        assert_eq!(get_init_sighash(0x5c79df1d0c587516051e670e2b4fdc124bb89eaa7b871e583c76de94879dee7.try_into().unwrap(), escrow, 0x4c217aa22943584a62094ddfd8d2b447fda0530666285081fd78e87ac365a4, 0xe3024f54ae2e3a21, 0x26cf8d5a7304867001eada079e2a68488bed935b35b0a49dbcd040c2d2ea9a5.try_into().unwrap()), 0x577ec86a5d8fcd7083a9af231209714e7c8548241f571f83e0757eb687ca9e7);

        let escrow = EscrowData {offerer: 0x32358666e00ad2baefb26714d03ddb91be6371a44ffd59329a7ee7f76883c0.try_into().unwrap(), claimer: 0x527534e6b4345335935f425d399d9775962bad3ecb38aefc3509c445890aac3.try_into().unwrap(), token: 0x7f28e902964d3887bf27595ce259237adc0ead7d3ac4672e8f8cc2bac1a8eae.try_into().unwrap(), refund_handler: 0x381f61df7a59d7672df7545eba5ab4340573c6de64fb5a6a711b0ffcfcd61cd.try_into().unwrap(), claim_handler: 0x2d16bfac828b5a1af675e42ae62818bc9270e6e63a6b0847ea32f4d04f4247f.try_into().unwrap(), flags: 0xe6bb2b0d2f7572bb2732c0b10add880a, claim_data: 0xbaed54651d846ca9c8dede9299c6715ac95ebe4978ddfa6ffa29f346bc4384, refund_data: 0x98be4779e59919128cfb850d7f6c2a5ad9e10e817b39646f8f58e4c3e3a8db, amount: 0xc0ca6a899aeeac39f4663d62320c3a53ce6c7c3be91209b2e30e87921c06b538, fee_token: 0x176ecbcd7f4f296a6ac75e4df2b7165a0f7b4afa90b0241bc9ae108483d1a74.try_into().unwrap(), security_deposit: 0x78b7e04555151ee940989c0d656fcceaa39ea4e314bb5fb0d279025e796474e1, claimer_bounty: 0x5e7af13af6000afdfeabfaaa0cc862c84dc8b33c48f9b4b602ad2b2e2ebe97a4, success_action: Option::None};
        assert_eq!(get_init_sighash(0x62686f8c4e7078049c1f90f6807558da01aa1f4caa147f7e95798e0e86026ce.try_into().unwrap(), escrow, 0xc08f29ced572527bd5cbba1b7fc5d0a200cfa226e2ad8698a7882e0cac9ec0, 0x473d7597faf12dba, 0x3aaa8715061d624326156742d8d05a0602c6467289d255125388387e3bd75c1.try_into().unwrap()), 0x599342e115d4f0e5556d3d3c7b143f065d3dee4ebc73d5788fb49a4ce51bf4b);

        let escrow = EscrowData {offerer: 0x3393dda500753e843ead6590d6cca0fcb7c2bd4787c5d8d6de8bf0a4e39d1bf.try_into().unwrap(), claimer: 0x4b617cba0cb91c5909d1bf45434013361951f8eb52eee2df4e896b62de3962c.try_into().unwrap(), token: 0x3f747abb0a009f3f4523ce61d7b59240e4a0d97b4bfc252ac5d0b012cf3eae9.try_into().unwrap(), refund_handler: 0x294e529b18b39faa6cff361a311293e058045aaefd752e30a4926ce802852ee.try_into().unwrap(), claim_handler: 0xd3a60b4c4cfff0831ea3d230b6491c089f5f7dda2bd751a74f2b2aecc8eb55.try_into().unwrap(), flags: 0x964106d617596d95d9cbeea0f8f7c493, claim_data: 0xe1eebe9a012b27f4a7bf51d72c24a903f86674bb514cfefbacd7b2be11f263, refund_data: 0x789d9e0eb27000e2d923048bf9f57af9d7dcf72558f77753bc28f5388d4664, amount: 0xdfb3fcb13e02c93fc3f37ed8aa361282b3f8adf32c3c3e1284c298b2782afc93, fee_token: 0x3f73418e25b979bf4a763a421aba32fa842ac8a8be84ade2b1bc405eff8092c.try_into().unwrap(), security_deposit: 0x5049dcfba74e3f7e7c7515543db71d6522316fbe323a931566858718cde16e0e, claimer_bounty: 0xcba4c26110d9c47315c8c81c206dbaf20597e3e573729e956750b93923247d0b, success_action: Option::None};
        assert_eq!(get_init_sighash(0x7c7724b501332d93ad3cc9f4feca87853d523f8c3d32a37ad5bd9698ee564.try_into().unwrap(), escrow, 0x3ebf14c6e1a5b2b964205757af6ed8c80469dd624897dd001752ce8643c5eb, 0x89e593c8cf85f6f5, 0x2f27c6c0e3d3010b12f7c6284d8c862ab6c96926b137b1984d88852628222df.try_into().unwrap()), 0x3b95475b1084978b03d3410894c12c4e658d78cca137dc44ffab4cf1408397a);

        let escrow = EscrowData {offerer: 0x76a49fc0c0deb282b70ad3a000cb0b7986b670844ec486f35391843139dc27a.try_into().unwrap(), claimer: 0xb107fbb8a30dee6615161f15ae9a42a935f047abe8324a0d0f7b43cdb79d8e.try_into().unwrap(), token: 0x570becd21869fbc336fd9244a588bc0f553d1c919767b14d8d331bcb002ae5b.try_into().unwrap(), refund_handler: 0x718396d2ed23814e597f571317ea1fe5bab7c58fb2b31675eb2c4636909c8fe.try_into().unwrap(), claim_handler: 0x174d45870d9dfbd24e043a228d85cea275e854cd6c4bc69615c159cc76c9272.try_into().unwrap(), flags: 0x3be3f83b526e2209a05d939b96bed409, claim_data: 0x8a72247c90e40cedc396700aac56cc309ebc944cf6c6e8de7201ed60ca09bc, refund_data: 0x75a4cb98b90b83fba92e8245dc195776a27b8b4485323b498b4a9a548b3bfe, amount: 0x6b2a5ba1072aa85da0d617fc3407ce607ed4a8ae4bc8e8f41bf9120ab1f54368, fee_token: 0x4118d06c0c09cf6c660ad161ba3481057bdef9167b48783c1125f555dbef855.try_into().unwrap(), security_deposit: 0xddea669d4afd56588e30491957062a886006ca077c44bef78aaa8d73bd5945f0, claimer_bounty: 0x7e9b546b3b5f7eaee67a83ed389fb47e86885f65c134f5e88b8f644768bffc8e, success_action: Option::None};
        assert_eq!(get_init_sighash(0x4813b1512c7448fadcf23a765b21c809198ff9cf4cc0c06a127ce8bf7bf6857.try_into().unwrap(), escrow, 0xcd0c1f6b11cdef8371ca9de89b1bcbb6c36704e4bcb69ffac9af54c118f7ca, 0x5576f0d7749e38d2, 0x3a12a21c00437bc11c596e47cbe07f29f732de7eb74f8c55ed854e5f52ef1a0.try_into().unwrap()), 0x75672e69c63d8b1cac983a6aaf7ba8bb42102cfca82dda54e41d7a40a3828b0);

        let escrow = EscrowData {offerer: 0x2bc31f857e8770fbdd0c17191944a6996be63cb107f840af86698b5a170ff6d.try_into().unwrap(), claimer: 0x4cafc518b123d6127ef30b9d788d478c267c1d2c667aead5096b97e4aa19ac6.try_into().unwrap(), token: 0x5076b32f96985c358fb6339001ea41dbd9f08f5c35861e746d4a8e54be4bac7.try_into().unwrap(), refund_handler: 0x3bbc2a066bad2e714604dfc81d97d1d7949615aaab41ee03fae43fa72da0790.try_into().unwrap(), claim_handler: 0xe00ae271e7f1ad64d6476a26ce54848b069bd36a587c4f5ad811b9f0bd4229.try_into().unwrap(), flags: 0xe84b1119a1e877cce8853e4544a716c9, claim_data: 0x11845654108b16ec073e0c905342764e3d9c06e54b318636f15b2228d83a85, refund_data: 0xb69f2b3d1b086bcabbe4093b80725b80c0693680dcd4b3010950026d92031d, amount: 0x5fbfed8f098970ceb0d132ca8197b34a796bf6fd771e76c4736354e01088243b, fee_token: 0x76450b098927d84e040f43f724a40a214fe7eb073f70f0b2e3110b1dcfece47.try_into().unwrap(), security_deposit: 0x49b72ce45b92f7b5a55775ff8b49422c6e021a0a614348d71e98b6731ffd8de2, claimer_bounty: 0x08815dbc4e91d49a0e9860ae90a2df0ace6d1b6d11eaa684333be1238eb23694, success_action: Option::None};
        assert_eq!(get_init_sighash(0x18e2164e4586250f74e9530de214f857134254313319eced409072cd71ada2b.try_into().unwrap(), escrow, 0x4cd37f1b3cffa8ac8cecc6cc7b4b0930b1319140056d0ff262a787242fe2a2, 0xa369d2a4c916b982, 0x1ed366442fb70bc0b16805eb3028cc39dab6747d8949948058d6fce0b76463a.try_into().unwrap()), 0x31098f073b357e365dc6c7d24e9f7b14cb5836da9dd3f830b2842d95a111295);

        let escrow = EscrowData {offerer: 0x18632938c1c35e3b93286387dcd6faa545806fdbb3f087634915a234f646010.try_into().unwrap(), claimer: 0xe7423b0011d212876d09729aaefe9159ca22ff30d00fd0787bbf18cabbd037.try_into().unwrap(), token: 0x2b5198f19dea962ce6ac5a46300ebbf1c5d48d4ad5b3ba010f0463019b8bdb5.try_into().unwrap(), refund_handler: 0x2f9d12a1516eaa6b89826f663ae3959f0b891084745e8b780831c7a13d50231.try_into().unwrap(), claim_handler: 0x4a842f669abc87572cb5b76530d67e6749f0c77630168c2d509345f76b656bb.try_into().unwrap(), flags: 0x44aac4baf52f65c47ddbf74337db02db, claim_data: 0xd8c796d166e49b2665ee93f8bc518747f5c2c1680cd5f78e563e853a666052, refund_data: 0x9cd384663a79eac6616ce65b569e6d3a169ccdcfa5fdf0748e32189a73b709, amount: 0xd19b66cdc074fad63c00d7fadc2a8952866aaf6b026d765bdad8cacf9beca678, fee_token: 0x2e2c695fc6081bb6b0b070e0635582c6984f2e442d8226c5e44dc4342411579.try_into().unwrap(), security_deposit: 0xa3da2aea4e3f8c113d6eb149d9240c408320e681679c3c52fe17e9963eb3a5fb, claimer_bounty: 0x05373f13cc3d9073246573abca32a147611ea4a0d25cf8e8aad8cb795aa0a14e, success_action: Option::None};
        assert_eq!(get_init_sighash(0xeebbd76ca315f1406f821470b0bc2a926164446f2ceff2e23cfbb7fc0b688f.try_into().unwrap(), escrow, 0xbd1cf29ea3447fc605d51ab94b5ad843114e6cede16199737feb91e1dca8d6, 0x1fbb73c55f9ca0e8, 0x62e3447fcef88d7660619dd344cf2b6c1d5c4d7850f9236d4ba19dbb58bbad7.try_into().unwrap()), 0x6cc444e30dce8590b9b7d1c06d5a8f072f32c17db51f7f77e5d46d86bb4979);

        let escrow = EscrowData {offerer: 0x59c2f64f06754cabe4623be40d0736235bf4cce07179dec47bfa7c2bd4b04b4.try_into().unwrap(), claimer: 0xea6a425d3e8d5921a718f0e4ca5efc48927b7496c83b583397855d9498095a.try_into().unwrap(), token: 0x54e964178c7ec63a5fba59fde3dad2cb242f2679c7cef66a55498d76e1cb169.try_into().unwrap(), refund_handler: 0x4d1b9f8c724634a4e784cffd9a42a1e864c0a5f7158cd7f0e34a1582ee203fe.try_into().unwrap(), claim_handler: 0x7826b7dcaeeb0b529c53b8baf7a70bcff2a15e348f4cea7ecda633c690c981e.try_into().unwrap(), flags: 0xcd23b28a83d5d617b272adac4a40b890, claim_data: 0x42d628b38d16dcc7d90fe89b00c504a4db4832708210015ef2dc3e80d060e0, refund_data: 0xfc455a6a66ca887de15a34cccb4efcd14c82fde021b8faf4bbd750a2ae7804, amount: 0xc57d3ee8728b884224edfff4587bddd8e0439e6e454603df9fce8fb091927e59, fee_token: 0x6cf2fd84c3bad116852d2edd925e0240cd4eb9d0bafd789bb91e1e83ebac46.try_into().unwrap(), security_deposit: 0xf91bafa6e5a5f539598266300cd6120ed805b41386ad6c9ff7a7cb6821030a8a, claimer_bounty: 0x14e24a5adc994339e33635e158fc09100ae7b6d3718f51fdc26db9e9db2fac2d, success_action: Option::None};
        assert_eq!(get_init_sighash(0x59ae4631c6d9de64229a50d0de5890984fd2516d55660a66ee84af9792b9863.try_into().unwrap(), escrow, 0x48552711d84a55eaf3c834822aedd20117a330572e14b9825173748bf065e0, 0x5c95e5e6eda45cf2, 0x790cf5649dcdd6c4a26caea2748920f6edbe904d9c0c76c9c7469a35dc4ea53.try_into().unwrap()), 0x3d0ad59f34df52c9e922e559aef85c37e7ebd8e83aa8a02496b05a5dccf8da7);

        let escrow = EscrowData {offerer: 0x7360ebf4bf2e622e46b1c9b0db4bc69a1814fde140358713d23d51203a63afe.try_into().unwrap(), claimer: 0x523bd179f7e9d71022bc45835e159dd07ac38eb390c4e9bdb59384ea7cf3c4d.try_into().unwrap(), token: 0x2b4e99a7f5cb2dcfbcfc1641c6d67ed41994b64dae9198c55e6eb6f4ac87944.try_into().unwrap(), refund_handler: 0x73ad465860cc2d6f0545e97064d4b106f3bd92d16c93623896302985187c298.try_into().unwrap(), claim_handler: 0x5ae50cd491469425b6588ea4d53e85926c6c2d03903c21bc441a28a3774a232.try_into().unwrap(), flags: 0xff3749d1144c85a0cac79b863bbfccb, claim_data: 0x4cb6240b61b3d771cdb9a140fb48f75edd4103268f5b96953ca76934a5afe7, refund_data: 0xb3605fb6c13bd5eb5bf0fc9892a590c93c852270f043c64201c33d7008f93f, amount: 0x466df01b352de37e8a817faa42ede37a8705ce2da2a9af4b695ec2ee44c8e163, fee_token: 0x33901294baba6d6bb5ab899a3abba9c5159db43e828a1974a18f80c4c9b3714.try_into().unwrap(), security_deposit: 0xc3c655b2290743dde093a61818683c34cabc67c476a155049457046e1d8a572e, claimer_bounty: 0xc12a70721871581779a37cdf4db8c1ecb042719a2a30ec07e4810a290c85ba7c, success_action: Option::None};
        assert_eq!(get_init_sighash(0x4ea91a3c3547ba8aac186c5f8fae200a2ec405cde92dfab6ed025ea44fa41f0.try_into().unwrap(), escrow, 0x579ba2ef54da3ed78961607fe0ca3e887b23aac86ed850ec7ab5fc360f7eeb, 0x5c51ebaa88525438, 0x7b92728013362ed73dfcede1ba58828bc8b71e0a2231945272a97895bb43af.try_into().unwrap()), 0x5f71dd18d32c7c98db64182075e088c871a6f435e5ef1b21e41010a07db72be);

        let escrow = EscrowData {offerer: 0x4d5239ae4b58106921c21d20ec9155f4ad46e0706e405839f1c79954897e244.try_into().unwrap(), claimer: 0x7cccb8bafd8c232c6ae82bcea0673ec256ce20036052d74690ae11685f65d00.try_into().unwrap(), token: 0x53143698b77974bec6db954d969bfa476cf5d8a576c0bf0844d250841420b37.try_into().unwrap(), refund_handler: 0x15947c8e0b7a9570974dc2c310db986a8f17f129cdb11c34edd61ac96af04f2.try_into().unwrap(), claim_handler: 0x6869aad069721dab10351468b282879f3d9ec5414e9b3a3858de2057e422025.try_into().unwrap(), flags: 0x94a478ca606947d15dab4dfbccd97d8d, claim_data: 0x0805e3f245590e68f2f761b14c84777f0d7b2b2f517f1489a52cdeec1e19a2, refund_data: 0x4e643da4a18457fc231875642003a7bffbd7db2e6537f27fd92ae35b750185, amount: 0xe8b7c8c51d2ad0d65256e76e2ef059f1ee6253f3828fdbca0ebb570df1b4096a, fee_token: 0x29170b49eba969edcf8f6f943cb10eac64a83325bd164bb50da2551ebb323b.try_into().unwrap(), security_deposit: 0xad13ffaaee5487378cf6a0508f3793940cbfd198a132979384eef805eb7cf0da, claimer_bounty: 0xaef7a9dbf3c39c682514fcf9b41a7ac7dbdc4bb8b8da5cd31de9b78a8d61513e, success_action: Option::None};
        assert_eq!(get_init_sighash(0x144b290dc99312cd6dc2b3d0e16f4c30511e0704d61fa3f97af1759965f053d.try_into().unwrap(), escrow, 0x0c68ab5478bbb4cc4a714dd6251fbd3cd4d4967b6a72eabe4d8c9b821e84a3, 0xb7b51fab339e4804, 0x62460e920daf7fb373a345c7802b9e548c703389eee3a330a390b46ac316ff1.try_into().unwrap()), 0x41d9fe86714779344f82be983b2953848d1f7f857d21fd866754caaf2f6adeb);
    }

    //Test cases generated by scripts/tests_unit/sighash.js
    #[test]
    fn random_refund_sighash() {
        assert_eq!(get_refund_sighash(0x516cbcc24aff8f5090a859e320e9de2bca9a0da7744f86b75485c8128e5fe48.try_into().unwrap(), 0xd8a6a89985484dc95ef2b56a4ebadcf24e34bde21822a7b9287e13ad1180c5, 0x8a3313d20fe79882, 0x335e30f785decd66a57ae2044e307779b0787262c2fbe47a7ecfb5b775c8e3a.try_into().unwrap()), 0x42888473f13bf32138e64a72afc06cba7dcc2b18a4a74cbf3029c439e4fd447);
        
        assert_eq!(get_refund_sighash(0x70d465ae75cdf0a4145a4c97c9e1e27f44b6791088ceb2a72576b9cc124ccf0.try_into().unwrap(), 0x5168f35480d5f4eda06d902e5311a1dd89a4d3cf7411ea845e1da28e18cca5, 0x9ede878124f79a97, 0x496c933c07ebf869dc260555c25ae6b95d35169dbf396fd4c3cd67f0fb9213e.try_into().unwrap()), 0x44700dfa689fe37a4e806cd5b9d93a2715c95c6a00ae33de8189f1f0f67bbf5);

        assert_eq!(get_refund_sighash(0x4752a28313f7872c789cdc222768108bbe9dfd19bc1a348de5b7f2463dd693d.try_into().unwrap(), 0xb0509710ab882077321ad0525313477587a3da242933a4a127478c744ee7af, 0x43e896799f66fb75, 0x2719a41866bebfb543e982c4db361585e5cf8431d29ab546cd16a7d214eeb26.try_into().unwrap()), 0x4715478dc5d3dbda0ee458a63ad556cb842ffbcc12c5a61fc6118b3b0e6ed5f);

        assert_eq!(get_refund_sighash(0x303acf412f10d3c2c908f11371115c9f40c7d9b734597defd5831c2d2e06dc8.try_into().unwrap(), 0xd149e66526c953551217d787e0feee05bbe9bb01ab1e14a16c0fd2486c0357, 0xb86a87d5ac89682f, 0x33698859ab3567cd8f70bbeb78a34497820351aabb61a8ac058690a83d519ac.try_into().unwrap()), 0x33a0fb780f7981ee08365463c131e9ff99f2fe3faedfff3257556c25c08d016);

        assert_eq!(get_refund_sighash(0x75fb5e25bc888784f8eb9c3fd5b599b177a070bf28923b797b4ff6b2d3c5438.try_into().unwrap(), 0xdcca53999ae541bd7c1fe371ba1eb6df4f7e51e8c477c7d07bfacd0f71b385, 0x72524b0121ef8b23, 0x6bf77f3a403a26e300fcd1f66c00ae945811e5ed2743e836164cb220e3cd85f.try_into().unwrap()), 0x7c7e841fd3cb889f3952cbed1b9e8136312c4429d8cc7f74c232c21306227e);

        assert_eq!(get_refund_sighash(0x3422d53c79e7e99df96bf8b9f30d2ac70e9e610faffb28c1235fd225b2a89d.try_into().unwrap(), 0x0a81d7ceb88f47c4d03474189ecedaa84063d1f106822a37defca96157c05d, 0x08b44ccda5994f64, 0x95979639c822179fb1e81aa4265c2f2879c882be3b51af8c16abb968e7bfaf.try_into().unwrap()), 0x6e996dbb59c77d18c97fd912d9c87d4a798bad4a02a2491f7e2d78c4efa5469);

        assert_eq!(get_refund_sighash(0x753b7437d480916cdfaf8a7f029b41c7767f280c748b54076474db03b0330e5.try_into().unwrap(), 0xe61b31297ee5bcd5a13a8752b4101f9218d0103aff323a6bba5cabb9f300ee, 0x8eb3b0918015507c, 0xa20c5228c481a9dd2af2a429d0668b17ea342c9a9436ec4afd41e242530457.try_into().unwrap()), 0x28da51c479999b5147a05de59609f29c8bc31b0c2dfe8a270eb36a8438f674e);

        assert_eq!(get_refund_sighash(0x5ce359f9ddf9a9905f6c46fcf81f89ea5aeab9b1890fadeb267df467c09a7f.try_into().unwrap(), 0xedbfff12b5dfaa41161a3d6c5a434b818343b4d810d1495889a9b5327a84a4, 0x273599d800404b07, 0x40f676d750c3a804845fed74ccef785b482e384a4a7b67424191afc62fb276f.try_into().unwrap()), 0x576bde0209ec6590152e54cb7de4b766c4c3053f213404f414be80f205e6d37);

        assert_eq!(get_refund_sighash(0x3f16153eba14a15da65c802eacd1664ce52144a4692ab8300bc232d8726afbc.try_into().unwrap(), 0x77f8aae5351777da29bb02abf40a992a7df52d4773529f7ee8775144998a98, 0x11fe51667bdbb372, 0x6bb717448bcfb64433ecbc88c87d98bf35df6e2b0dd9a3f41f62e91e5df58e5.try_into().unwrap()), 0x16607da4991f287f6925cfe38ec2d298de06436479fbd04a60669aad706163a);

        assert_eq!(get_refund_sighash(0x2e5ed0b790c4b4aec8ee41dd00ebd9b54c9df0afa199ed1d03c1974fa8e7bb5.try_into().unwrap(), 0x06e9410a86849a0bc1537f927fc5910cd87b15fec1321fd86fd9e031a4c3fb, 0x74654045c93e5ed4, 0x259c43f645bba38f912f48e554779fa3e21cee6bc6ae516c371642c069c449d.try_into().unwrap()), 0x26d6e046bce98b6591791d894a0c54f201a3e63af2e1ad5285e549dcebf5a17);
    }

}