[package]
name = "btc_relay"
readme = "README.md"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[scripts]
test = "node scripts/generate_test_data.js; snforge test -F test --no-default-features"

[dependencies]
starknet.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true

[features]
default = ["release"]
release = []
test = []

[lib]

[[target.starknet-contract]]
sierra = true
